import { z } from "zod";

export const onboardingSchema = z.object({
  category: z.enum([
    "fmcg",
    "electronics",
    "mobile_accessories",
    "pharma",
    "apparel",
    "footwear",
    "textiles_fabric",
    "auto_parts",
    "two_wheeler_parts",
    "grocery",
    "hardware",
    "sanitary_plumbing",
    "electrical_goods",
    "paints_chemicals",
    "building_materials",
    "furniture",
    "musical_instruments",
    "sports_goods",
    "toys_games",
    "stationery_books",
    "gift_items",
    "cosmetics_beauty",
    "jewellery_artificial",
    "bags_luggage",
    "kitchenware_utensils",
    "plastic_goods",
    "packaging_materials",
    "confectionery_bakery",
    "dry_fruits_spices",
    "tea_coffee",
    "dairy_products",
    "agro_seeds_fertilizers",
    "cattle_feed",
    "tiles_sanitaryware",
    "glass_hardware",
    "computer_it",
    "printing_stationery",
    "cleaning_supplies",
    "fireworks",
    "readymade_garments",
    "saree_ethnic_wear",
    "watches_eyewear",
    "religious_puja_items",
    "other",
  ]),
  customerType: z.enum(["wholesale", "retail", "both"]),
  orderVolume: z.enum(["lt_100", "100_500", "500_2000", "gt_2000"]),
  warehouseCount: z.number().int().min(0).max(1000),
  staffCount: z.number().int().min(0).max(10000),
  painPoints: z.string().trim().max(1000).optional(),
  goals: z
    .array(z.enum(["inventory_tracking", "credit_payments", "multi_warehouse", "staff_management", "ai_insights", "reporting"]))
    .min(1)
    .max(3),
});
